#!/usr/bin/env perl

use strict;
use warnings;

use FindBin qw($Bin);
use lib $Bin;
use ItemScrape;

my @catagories = (
    trade_goods => {
        skip    => 1,
        id      => 'table-6-3-trade-goods',
        columns => [ qw(cost name) ],
        types   => [ '' ]
    },
    weapons => {
        id      => 'table-6-4-weapons',
        columns => [
            "cost", "dmg (s)", "dmg (m)", "critical", "range", "weight", "damage type", "special"
        ],
        types   => [ qw(simple martial exotic) ],
    },
    armor   => {
        id    => 'table-6-6-armor-and-shields',
        columns => [
            "cost", "armor/shield bonus", "maximum dex bonus", "armor check penalty",
            "arcane spell failure chance", "speed-30ft", "speed-20ft", "weight"
        ],
        types => [ '' ],
    },
    goods_and_services => {
        id      => 'table-6-9-goods-and-services',
        columns => [ qw(cost weight) ],
        types   => [
            'adventuring gear', 'special substances and items',
            'tools and skill kits', 'clothing', 'food and drink and lodging',
            'mounts and related gear', 'transport', 'spellcasting and services'
        ]
    },
);

while(my $category = shift(@catagories)) {
    ItemScrape->new({
        src         => 'http://paizo.com/pathfinderRPG/prd/coreRulebook/equipment.html',
        space       => 'core',
        category    => $category,
        scrape_opts => shift(@catagories) || die 'Odd number of elements',
    })
    ->scrape_html
    ->import_data;
}

